### ISSUE TITLE
很棒的程序！请问使用的哪种许可协议？

### ISSUE THREAD

**Issue by cuiliang** [LowPlayer/DrawTools#1]
谢谢！

**Comment by LowPlayer** [comment]
被你问得不知所措，刚刚添加了GPL许可协议

**Comment by cuiliang** [comment]
谢谢~

**Comment by cuiliang** [comment]
考虑提供商用许可协议的方案么？如果可以的话，大概需要多少费用？
我是[Quicker软件](https://getquicker.net/)的作者，有些用户会有编辑图片的需求作为工作流程的一部分，因此我在考虑如果有合适的组件，在软件里集成一个这样的模块给用户使用。

**Comment by LowPlayer** [comment]
商用许可协议的方案怎么提供？是要我一直维护吗？

**Comment by cuiliang** [comment]
不需要一直维护，大概意思就是许可一下可以在非开源的，商业的程序里使用代码。 
因为GPL本身是要求使用代码的程序要开源才可以。

**Comment by LowPlayer** [comment]
哦~这样，那应该用什么协议才能不开源使用

**Comment by LowPlayer** [comment]
我就是GNU Lesser General Public License协议，刚接触这些

**Comment by cuiliang** [comment]
现在一般用MIT的协议比较多，微软的.net core之类的都是使用MIT协议。不过这个根据个人喜好，可以完全自己定协议。 有一些组件是双协议，使用LGPL+商业授权协议。

**Comment by LowPlayer** [comment]
OK，那就改成MIT协议吧，你也太认真了吧

**Comment by cuiliang** [comment]
👍 谢谢~ 协议还是应该遵守的😁
